# Generated by Django 3.0.2 on 2020-01-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('tag', models.CharField(max_length=40)),
                ('url', models.URLField()),
                ('claps', models.IntegerField()),
                ('clapStr', models.CharField(max_length=30)),
                ('authur', models.CharField(max_length=40)),
                ('publication', models.CharField(max_length=40)),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-claps'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, unique=True)),
            ],
        ),
    ]
